# Generated by Django 4.2.4 on 2023-10-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_yoga_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga',
            name='dis',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
